name: make mv300 060

on:
  repository_dispatch:
  workflow_dispatch:
    inputs:
      set_chip_type:
        description: "Select Chip Type."
        required: false
        default: "hi3798mv3dmw"
        type: choice
        options:
          - hi3798mv3dmf
          - hi3798mv3dmw
          - hi3798mv3dms1
          - hi3798mv3dmm
          - hi3798mv3dml
          - hi3798mv3dma
      set_arch_type:
        description: "Select arch type."
        required: false
        default: "arm64"
        type: choice
        options:
          - arm
          - arm64

# 必须添加这个权限声明，否则无法创建 Release
permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Initialization environment
        id: init
        run: |
          sudo -E apt-get -y update
          sudo -E apt-get -y install gcc make gettext zlib1g-dev libncurses5-dev bison flex bc texinfo tree cmake flex lzma git
          sudo mkdir -p /builder
          sudo chown -R runner.runner /builder
          echo "status=success" >> ${GITHUB_OUTPUT}
          
      - name: make build
        id: build
        working-directory: /builder
        # 修正：去掉 ${{ }}
        if: steps.init.outputs.status == 'success' && !cancelled()
        run: |
          git clone -q --single-branch --depth=1 https://github.com/zsl7091/HiSTBLinuxV100R005C00SPC060.git mv300
          cp ${GITHUB_WORKSPACE}/config_files/${{ inputs.set_chip_type }}_hi3798mv300_cfg.mak mv300/cfg.mak
          cd mv300
          source ./env.sh
          make hiboot
          # 确保目标文件确实存在后再拷贝
          cp /builder/mv300/out/hi3798mv300/${{ inputs.set_chip_type }}/image/emmc_image/fastboot.bin /builder/fastboot_${{ inputs.set_chip_type }}.bin
          make linux -j2 2>&1  | tee -a buildlog.txt
          echo "status=success" >> ${GITHUB_OUTPUT}
          
      - name: Upload Kernel to Release
        id: tar
        uses: ncipollo/release-action@v1
        # 修正：去掉 ${{ }}
        if: steps.build.outputs.status == 'success' && !cancelled()
        with:
          tag: mv300_kernel_060
          # 建议 artifacts 路径如果报错，可以尝试去掉最前面的 / 
          artifacts: "/builder/fastboot_${{ inputs.set_chip_type }}.bin,/builder/mv300/out/hi3798mv300/${{ inputs.set_chip_type }}/image/emmc_image/hi_kernel.bin"
          allowUpdates: true
          token: ${{ secrets.GITHUB_TOKEN }}
          body: |
            - 海思3798Mv300内核 32位。
